version: '3.1'
services:
  backend:
    image: node:12-alpine
    command: sh -c "npm install express --save&&npm install nodemon -g&&npm install body-parser --save&& nodemon indexs "
    ports:
      - "4000:4000"
    working_dir: /home/nodejs/app
    volumes:
      - ./:/home/nodejs/app
    environment:
      WAIT_HOSTS: database:27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: api
      PORT: 4000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
